name: Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - test_task
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry'
        default: 'ghcr.io'
        required: false
        type: string
      server_address:
        description: 'Server address'
        default: 'smtp.gmail.com'
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/angular

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: start timer
        run: |
          echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
          echo The registry is ${{ inputs.registry }}
          echo The server_address is ${{ inputs.server_address }}